name: Perorno
favicon: null
layout_spectrum: 0.2814508315641433
typography_spectrum: 0.05049211415462196
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#eb9f4c'
    - '#d7c9db'
    - '#9a5d28'
  brandStrength: 0.7066139832604676
  lightness: 0.7890321670565754
  saturation: 0.1784317314159125
  rhythmicContrast: 0.5073150494135916
purpose: []
